# Generated by Django 3.2.18 on 2023-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('NS', models.CharField(help_text='Numero de serie del producto', max_length=20)),
                ('existencias', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
